spring.application.name=food-delivery-project

#MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/foodDelivery

#Cloudinary Configuration
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api.key=${CLOUDINARY_API_KEY}
cloudinary.api.secret=${CLOUDINARY_API_SECRET}
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:10MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:10MB}

jwt.secret.key=foodhub-your-very-long-secure-secret-key-2026
jwt.expiration=86400000
#razorpay configuration
razorpay_key=${RAZORPAY_KEY:rzp_test_SZWSEC6DpaIDJO}
razorpay_secret=${RAZORPAY_SECRET:w7kYfDAbzWPIEtZ4qwYHGQmd}