spring.application.name=food-delivery-project

#MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/foodDelivery

#Cloudinary Configuration
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api.key=${CLOUDINARY_API_KEY}
cloudinary.api.secret=${CLOUDINARY_API_SECRET}
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:10MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:10MB}

jwt.secret.key=${JWT_SECRET:q8Fh3kL8xP2mZ9wXgJtK2sYpR6vTnQ4uB1cD7eF9hG0=}

#razorpay configuration
razorpay_key=${RAZORPAY_KEY:rzp_test_SZWSEC6DpaIDJO}
razorpay_secret=${RAZORPAY_SECRET:w7kYfDAbzWPIEtZ4qwYHGQmd}